- name: "Container | MacOSX | Install Container"
  community.general.homebrew:
    name: container
    state: present
  when:
    - ansible_facts['architecture'] == 'arm64'
    - ansible_facts['distribution_major_version'] | int >= 15
